# Generated by Django 6.0 on 2025-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=5)),
                ('capital', models.CharField(max_length=50)),
                ('flower', models.CharField(max_length=50)),
                ('bird', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
