# Generated by Django 6.0 on 2025-12-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
