# Generated by Django 6.0 on 2025-12-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_state_id_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='states/'),
        ),
    ]
